/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugins/plugin-sandbox/src/extraMetadata.proto

package org.jetbrains.kotlin.plugin.sandbox;

public final class SandboxPluginMetadataExtensions {
  private SandboxPluginMetadataExtensions() {}
  public static void registerAllExtensions(
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite registry) {
    registry.add(org.jetbrains.kotlin.plugin.sandbox.SandboxPluginMetadataExtensions.sandboxIndex);
  }
  public static final int SANDBOX_INDEX_FIELD_NUMBER = 17100;
  /**
   * <code>extend .org.jetbrains.kotlin.metadata.Class { ... }</code>
   */
  public static final
    org.jetbrains.kotlin.protobuf.GeneratedMessageLite.GeneratedExtension<
      org.jetbrains.kotlin.metadata.ProtoBuf.Class,
      java.lang.Integer> sandboxIndex = org.jetbrains.kotlin.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        org.jetbrains.kotlin.metadata.ProtoBuf.Class.getDefaultInstance(),
        0,
        null,
        null,
        17100,
        org.jetbrains.kotlin.protobuf.WireFormat.FieldType.INT32,
        java.lang.Integer.class);

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
